/*
KEY:
+       Positive        +
-       Negative        -
>       Mass Update     >
%       Unknown         %
*       Bug Fix         *
$       Miscellaneous   $
*/

export var CText = [
    `Beta v2.46 - 01/13/2026`,
    `> MASS OVERHAUL:/~`,
    `$ Updated the ZS Changelog/~`,
    `$ Modified the Changelog to have more personality/~`,
    `$ Changed repeated scripts to be automatic instead of manual/~`,
    `$ Changed the main font/~`,
    `- Removed the developer console/~`,
    `- Removed the Itch portfolio link/~`,
    `+ Added the game dashboard/~`,
    `$ Wrapped TZP in a new project dashboard page/~`,
    `$ Wrapped "HQ - Countdown" in a new "Upcoming" page/~`,
    `$ Changed the website title/~`,
    `$ Updated the domain to https://z4ckstudios.com/~`,
    `* Fixed mobile view/~`,
    `+ Brought back dock animations/~`,
    `$ Updated URL scripts to make hiding file extensions easier/~`,
    `$ Fixed TZP code input area/~`,
    `$ Made TZP directory more mobile friendly/~`,
    `$ Versions are now listed on the changelog/~`,
    `$ Moved dates next to versions on the changelog/~`,
    `$ Made some creative changes to the URL to bring a more lively feel to the website/~`,
    `- Removed personality introduction to make the website feel more professional/~`,
    `$ Fixed the LED background for mobile devices/~`,
    `* Fixed the bug requiring the user to reload the page when pressing the "PAGES" button in order to change dock visibility/~`,
    `$ Updated the changelog to show newer events first/~`,
    `Beta v2.10 - 07/18/2025`,
    `+ Added more information to the Zen ARG/~`,
    `- Removed more useless information from the Zen ARG/~`,
    `$ Switched pixels to viewport widths/~`,
    `$ Polished the code input background under /TZP/~`,
    `$ Fixed a small grammar mistake on the Zen ARG/~`,
    `Beta v2.08 - 07/08/2025`,
    `> THE OVERHAUL UPDATE:/~`,
    `$ Simplified hundreds of lines of code/~`,
    `$ Made all code files developer friendly/~`,
    `+ Added an if statement to check if the BaseURI is on the website instead of the localhost/~`,
    `$ Anything branded with "ZS" is now just its' own file name/~`,
    `$ Fixed all file paths to be consistent with my other projects/~`,
    `$ Made the Changelog easier to add onto/~`,
    `$ Changed unecessary TZP ARG components into useful information/~`,
    `Beta v1.76 - 03/01/2025`,
    `+ Added more information to the TZP ARG/~`,
    `* Fixed mobile positioning bug with the eventTimer element/~`,
    `* Fixed a smaller URL bug/~`,
    `Beta v1.71 - 02/28/2025`,
    `+ Added TZP.html ARG/~`,
    `* Fixed some mobile style bugs/~`,
    `* Fixed a small Audio bug/~`,
    `* Fixed 2nd hand Audio bug/~`,
    `$ Updated Audio file path in JS/~`,
    `+ Added more useful information to the TZP ARG/~`,
    `+ Added extra codes/~`,
    `Beta v1.65 - 02/20/2025`,
    `$ Updated styles to run on multiple platforms with no hassle/~`,
    `* Fixed a small URL bug/~`,
    `* Fixed portrait identifier bug/~`,
    `* Fixed secondary portrait identifier bug/~`,
    `Beta v1.60 - 02/12/2025`,
    `$ Updated image paths/~`,
    `+ Added developer console determined by IP/~`,
    `+ Added ZSAC button/~`,
    `+ Added ZSIPortfolio button/~`,
    `* Bug fixes/~`,
    `* Small bug fix/~`,
    `* Developer Console bug fix/~`,
    `$ Developer Console IP command fix/~`,
    `+ Added extra mobile support/~`,
    `Beta v1.35 - 01/29/2025`,
    `$ Changed the background for CS - Countdown/~`,
    `$ Updated DisC to CS/~`,
    `- Removed DisC Logo/~`,
    `* Fixed small URL bug on index.html/~`,
    `* Fixed CS.html URL bug/~`,
    `Beta v1.28 - 01/07/2025`,
    `$ Updated "Page1 #+" names/~`,
    `+ Added page rule for display upon id/~`,
    `+ Added phone styles for Page modifiers/~`,
    `* Fixed button positioning for mobile devices upon Docks/~`,
    `$ Simplified logo positioning for both PC and Mobile platforms/~`,
    `$ Changed DisC background size to 100% NR (x50, y50)/~`,
    `- Removed user-select/~`,
    `$ Updated Discord server link/~`,
    `$ Updated DisC background position to x50, y0/~`,
    `$ Updated DisC background position to x50, y27/~`,
    `$ Added the "t" in "CS Coundown" (that is a terrible habit)/~`,
    `$ Changed "FL - Main Panel" to "TZP - Main Panel"/~`,
    `Beta v1.23 - 01/02/2025`,
    `+ TZP Forbidden Entry/~`,
    `$ DisC release updated to: February 1, 2025/~`,
    `* TZP FE bug fix/~`,
    `$ DisC + TZP mobile config color swapped/~`,
    `$ DisC HB position matched with TZP HB position/~`,
    `* Fixed DisC timer bug/~`,
    `+ Re-Added the main DisC background/~`,
    `Beta v1.22 - 11/12/2024`,
    `> TZP Page update/~`,
    `+ Added images to SM text/~`,
    `Beta v1.19 - 11/03/2024`,
    `* Fixed Times New Roman base font/~`,
    `+ Added "Season 1" button/~`,
    `Beta v1.14 - 11/01/2024`,
    `+ Added TZP menu/~`,
    `$ Linked TCTS text to "Fallen Lands - Teaser Trailer"/~`,
    `* Fixed window encounter bug/~`,
    `+ Added phone styles for TZP/~`,
    `* Fixed TZP mobile styles positioning bug/~`,
    `Beta v1.10 - 10/31/2024`,
    `* Fixed timer red on minute value of 0/~`,
    `$ Extended TZP release by 1 hour/~`,
    `$ Extended TZP release by 30 minutes/~`,
    `$ Extended TZP release by 15 minutes/~`,
    `Beta v1.05 - 10/30/2024`,
    `$ Timer units/~`,
    `* Disappear on value 0/~`,
    `* Red on (ONLY) 10s/~`,
    `- File extensions removed from view/~`,
    `* Smooth URL view/~`,
    `$ Fixed text-wrap for page labels/~`,
    `$ Rolled back TZP timer/~`,
    `Beta v1.04 - 10/26/2024`,
    `* Previous branding/~`,
    `Beta v1.01 - 10/22/2024`,
    `$ File path change/~`,
    `* Page discovery/~`,
    `+ Element dragging/~`,
    `+ User select enabled/~`,
    `Beta v1.00 - 09/24/2024`,
    `$ TZP release date change/~`,
    `$ DisC release date change/~`,
    `Alpha v0.96 - 08/21/2024`,
    `$ Portrait indicators/~`,
    `+ "Back Home" button on CdP (Countdown Pages)/~`,
    `$ Correction size for mobile devices on CdP/~`,
    `$ Quick changelog edits/~`,
    `Alpha v0.94 - 08/19/2024`,
    `> The mobile update/~`,
    `$ Extra mobile configurations/~`,
    `* Mobile bug fixes/~`,
    `Alpha v0.87 - 08/10/2024`,
    `% Beta in 0.13/~`,
];

export var CNum = [];

for(let i = 0; i < CText.length; i++) {
    var C = document.createElement("p");
    CNum.push(C);
}